<?php
/**
 * Created by IntelliJ IDEA.
 * User: User
 * Date: 06.03.2017
 * Time: 14:27
 */

namespace andyharis\yii2apigql\components;


use yii\db\ActiveRecord;

class Yii2ApigqlRecord extends ActiveRecord
{
  const ACTION_NOTHING = false;
  const ACTION_ADD = 'add';
  const ACTION_EDIT = 'edit';
  const ACTION_DELETE = 'delete';
  public static $messages = [
    'required' => 'Required',
    'email' => 'Not a valid email'
  ];
  public static $postAttributes = [];
  public $action = self::ACTION_NOTHING;
  public $oftenUsed = false;
  public $lastTouch = false;
  public $alias = 't1';
  public $table = 'table';

  public function generateAlias()
  {
    $letters = array_merge(range('a', 'z'), range('A', 'Z'), range(0, 9));
    $alias = 't_';
    for ($i = 0; $i < rand(5, 11); $i++)
      $alias .= $letters[array_rand($letters)];
    $this->alias = $alias;
  }

  public function getPK()
  {
    return self::primaryKey()[0];
  }

//  public function beforeSave($insert)
//  {
//    if (!$this->iID)
//      $this->iID = UuidHelper::uuid();
//    try {
//      if ($this->lastTouch) {
//        if ($insert) {
//          $this->date_created = strtotime('now');
//        }
//        $this->date_touch = strtotime('now');
//      }
//    } catch (\Throwable $e) {
//
//    }
//    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
//  }

}